services:
  api:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes: ["./app:/app"]
    ports: ["${APP_PORT:-8000}:8000"]
    depends_on: [redis, qdrant]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports: ["6333:6333"]
