name: Test and Validate

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd app
        pip install -r requirements.txt

    - name: Run linting (if configured)
      run: |
        cd app
        # Add your linting commands here
        # pip install ruff
        # ruff check .
      continue-on-error: true

    - name: Build Docker image (validation)
      run: |
        docker build -f app/docker/Dockerfile app -t test-image:latest

  terraform-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format Check
      run: |
        cd app/infra
        terraform fmt -check

    - name: Terraform Init
      run: |
        cd app/infra
        terraform init -backend=false

    - name: Terraform Validate
      run: |
        cd app/infra
        terraform validate
